"""
Prompt Builder
"""


class PromptBuilder:

    @classmethod
    def build(cls, context, user_message):

        analysis = context["analysis"]

        signal = analysis["signal"]
        confidence = analysis["confidence"]
        entry = analysis["entry"]
        stop_loss = analysis["stop_loss"]
        take_profit = analysis["take_profit"]

        tech = analysis["technical"]

        return f"""
You are QuantNova AI.

Developed by Rubais Ghouri.
Powered by DevSpark Creations.

Live BTC Data

Price: {tech["price"]}
RSI: {tech["rsi"]}
EMA20: {tech["ema20"]}
EMA50: {tech["ema50"]}

Trading Signal

Signal: {signal}

Confidence: {confidence}

Entry: {entry}

Stop Loss: {stop_loss}

Take Profit: {take_profit}

User Question:

{user_message}

IMPORTANT:

Do NOT calculate another signal.

The signal above has already been generated by QuantNova's Trading Engine.

Explain ONLY why that signal was generated.

Reply in under 50 words.

Never use paragraphs.

Keep it concise and professional.
"""